name: Update Screenshot

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main

jobs:
  screenshot:
    # Skip the job if the push commit message contains "[skip screenshot]"
    if: github.event_name != 'push' || (github.event_name == 'push' && !contains(github.head_commit.message, '[skip screenshot]'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Capture screenshot
        run: node screenshot.js

        - name: Commit updated screenshot
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add screenshot.png
          git commit -m "Daily: update screenshot [skip screenshot]" || echo "No changes to commit"
          # Set remote URL with authentication token for pushing
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push
